containers:
  # Java版
  java:
    # Mod Server (Paper)
    - name: mc
      newline: lf
      stopTimeout: 120s
      worlds:
        - /server/world
        - /server/world_nether
        - /server/world_the_end
schedule:
  interval: 12h
trim:
  trimDays: 2
  keepDays: 14
  minKeep: 2
