services:
  mc:
    container_name: mc
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "2048M"
      MAX_PLAYERS: "30"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      TZ: "Asia/Tokyo"
      OPS: |-
        test
      PLAYER_IDLE_TIMEOUT: "300"
      MANAGEMENT_SERVER_ENABLED: "false"
    volumes:
      - "./data:/data"
    restart: unless-stopped

  # =================================================== #
  #   Backup container service for Minecraft            #
  # =================================================== #
  backups:
    container_name: mc_backup
    image: kaiede/minecraft-bedrock-backup
    tty: true
    depends_on:
      mc:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./data:/server
    environment:
      TZ: "Asia/Tokyo"
      CONFIG_DIR: "/backups"
    restart: unless-stopped

  ddns:
    container_name: mc_ddns
    build: .
    restart: unless-stopped
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      CLOUDFLARE_ZONE_ID: "${CLOUDFLARE_ZONE_ID}"
      CLOUDFLARE_RECORD_ID: "${CLOUDFLARE_RECORD_ID}"
      CLOUDFLARE_DOMAIN: "${CLOUDFLARE_DOMAIN}"
      UPDATE_INTERVAL: "${UPDATE_INTERVAL:-300}"