x-minecraft-environment: &minecraft-environment
  EULA: "TRUE"
  MEMORY: "1024M"
  USE_AIKAR_FLAGS: "true"
  USE_MEOWICE_FLAGS: "true"
  ONLINE_MODE: "FALSE"
  OPS: |-
    test

x-minecraft-service: &minecraft-service
  image: itzg/minecraft-server:latest
  tty: true
  stdin_open: true
  restart: unless-stopped

services:
  lobby:
    <<: *minecraft-service
    expose:
      - "30066"
    volumes:
      - "../generated/lobby:/data"
    environment:
      <<: *minecraft-environment
      LEVEL: "lobby"

  survival:
    <<: *minecraft-service
    expose:
      - "30067"
    volumes:
      - "../generated/survival:/data"
    environment:
      <<: *minecraft-environment
      LEVEL: "survival"

  construction:
    <<: *minecraft-service
    expose:
      - "30068"
    volumes:
      - "../generated/construction:/data"
    environment:
      <<: *minecraft-environment
      LEVEL: "construction"

  streaming:
    <<: *minecraft-service
    expose:
      - "30069"
    volumes:
      - "../generated/streaming:/data"
    environment:
      <<: *minecraft-environment
      LEVEL: "streaming"

  ktc-survival:
    <<: *minecraft-service
    expose:
      - "30070"
    volumes:
      - "../generated/ktc-survival:/data"
    environment:
      <<: *minecraft-environment
      LEVEL: "private"

  velocity:
    container_name: mc_velocity
    image: itzg/bungeecord:latest
    tty: true
    stdin_open: true
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 256m
    ports:
      - "25577:25577/tcp"
      - "25577:25577/udp"
    volumes:
      - ../generated/velocity:/server
    restart: unless-stopped